### ISSUE TITLE
no data exported if no UIN in properties ?

### ISSUE THREAD

**Issue by guihomework** [patric-r/ICQExport#2]
Hi, 
thanks for writing such an app.
This java exporter is the first app that tries to do something on my old ICQ logs (all others did nothing), but although the app says

```
ICQExport - exports ICQ database files (prior to version 2003b) to HTML
Processing dat file
No UIN found inside properties!
(...) lot of times
No UIN found inside properties!
149769 messages extracted. Writing output files...
Done!
```
in the end the exported htmls do not contain messages (barely 180 bytes size) , and I don't recognize the UINs either (my friends had shorter ones that the one extracted)

I suspect that the few exported htmls are some UIN that existed but had no messages (spam?), whereas the messages without UIN, had content but were not exported due to missing UIN  ? is that possible ?
The .dat I have is from 2005 and is 65 MB but I suppose it is compatible as the software is doing something.

With a hex reader, I could see some ansicpg1215 which I suppose is for cp1215 encoding and there is definitely pure text there, just in lots of chunks, which I had hoped would be reconstructed with your software. So data is there.

I know cpp and python but unfortunately not java. I might find tutorials on how to build (seems like I need some build tool to also build dependencies like some com.google.common.base), but any hints on what could cause the issue might help.

thanks

**Comment by patric-r** [comment]
Hi, only ICQ database versions up to 2003b are currently supported.
After this version, ICQ completely changed the file format (imho dbf based) making it incompatible to the older ones.

If I have time, I might come up with a release that supports more recent ICQ versions as well but don't expect anything soon/no guarantees
(PRs are welcome!).

**Comment by guihomework** [comment]
I had a look at the header of the `.dat` file and to me it seemed to be ICQ version code `0x13` (so 19) from [this](https://commons.erau.edu/cgi/viewcontent.cgi?article=1010&context=jdfsl) and this matched what you wrote, so should be supported. I just wondered if you think that a missing UIN might be the reason for your app to not output any messages although they are there.

**Comment by patric-r** [comment]
if the byte at offset 0x10 is really 0x13, it looks like the database version is indeed good/compatible 
(I just got confused as you wrote that its from 2005 and I assumed "ICQ 2005").

In case you really see nothing in the export but unknown UINs with 0 zero messages
This might been a bug in ICQExport. I've only tested it on my personal ICQ databases so far.

Are you willing to share your database file(s) (the first few kilobytes would be sufficient for an initial analysis)?

**Comment by guihomework** [comment]
sorry for the confusion. I will have a look and what my messages are about. Is there some kind of private messaging in github to not have that data snippet out in the world ?

**Comment by guihomework** [comment]
@patric-r the fix you provided for my database works nice. Indeed there are no nicknames associated, but all UIN are now there, with all the messages now valid and visible. This is so cool to be able to read such old conversations in a nice flow instead of all messed up in the .dat.
thanks a lot !

**Comment by patric-r** [comment]
Thanks for your support!
I think that the user data is missing (which lead to this bug) as well if you haven't authorized the UIN as "friends".

**Comment by guihomework** [comment]
I think my most talked to UIN were "friends", but I must say I forgot which concepts were used in ICQ. 
I have also a 50 MB <UIN>.idx file. Would this one contain the missing info about the contacts ?

**Comment by patric-r** [comment]
Nope, the .idx file is IMHO only an index (which contains redundant info from the .dat file and no new information).

**Comment by guihomework** [comment]
I see. Thanks.

**Comment by patric-r** [comment]
I've published a new release (slightly improved to the beta version, adjusted texts in case of missing user data) so everyone can benefit from the bugfix.
